

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.140.128:3306/stock-analyzer
    username: root
    password: Root@123
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

mybatis-plus:
  mapper-locations: classpath*:cn/javacoder/stockanalyze/common/mapper/xml/*Mapper.xml
#server:
#  tomcat:
#    basedir: D:/workspace/stock-analyzer/stock-analyzer-web
#
#pathPlaning: costBased